#Purpose: To schedule the merging of open pull request to off-peak hours. 
#Requirements:  The following conditions must be satisfied for merging to occur.
    #1. pull request have a review status of 'APPROVE'
    #2. pull request title contains a trigger_phrase as set below
    #3. pull request status checks are all green (paased)

name: PR Merge Scheduler

on: 
    schedule:
        # run the workflow everyday at 6:30AM(UTC) i.e 2:30AM(EST)
        - cron: '15 4 * * *'

jobs:
    schedule_merge:
        name: schedule merge
        runs-on: ubuntu-latest
        env:
            # Defining enviroment variables for the job
            TARGET_REPO: idlagit/prmerger
            TRIGGER_PHRASE: '@schedule-merge'
            OPEN_PR_FILE: file_open_prs.txt
            MATCHED_PR_FILE: file_matched_prs.txt
            CHECKS_RESULT_FILE: file_checks_result.txt
            PASSED_PR_FILE: file_passed_prs.txt
            MERGED_PR_FILE: file_merged_prs.txt
            UNMERGED_PR_FILE: file_unmerged_prs.txt
 
        steps:
            - name: Get list of open pr
              run: |
                #clear out the file content if already exist and retrive a list of open pull requests and write output to a file
                > $OPEN_PR_FILE

                # retrive a list of open pull requests and write output to a fil
                gh pr list --repo $TARGET_REPO --state open --json number,reviewDecision,title --jq '.[] | "\(.number) \(.reviewDecision) \(.title)"' > $OPEN_PR_FILE

            - name: Get list of approved pr with matching trigger_phrase
              run: |
                # sanity check that file is not empty or missing
                if [ ! -s "$OPEN_PR_FILE" ]; then
                    echo "Input file '$OPEN_PR_FILE' is empty or missing"
                    exit 1
                fi
                
                # clear out the file content if already exist
                > $MATCHED_PR_FILE
                
                # filter open pr's that are 'APPROVED' and contain the trigger phrase in title
                counter=1
                while IFS= read -r line; do
                    review_decision=$(echo "$line" | awk '{print $2}') 
                    if [ "$review_decision" == "APPROVED" ] && [[ "$line" == *"$TRIGGER_PHRASE"* ]]; then
                        echo "$line" >> $MATCHED_PR_FILE
                        echo "Match found on line $counter"   
                    else
                        echo "No match found on line $counter"  
                    fi
                    counter=$((counter+1))
                done < $OPEN_PR_FILE 
                echo ""

            - name: Get list of pr with all checks passed
              run: |
                # sanity check that file is not empty or missing
                if [ ! -s "$MATCHED_PR_FILE" ]; then
                    echo "Input file '$MATCHED_PR_FILE' is empty or missing"
                    exit 1
                fi

                # clear out the file content if already exist
                > $CHECKS_RESULT_FILE
                > $PASSED_PR_FILE

                # Validate if all checks for each PR have passed
                while IFS= read -r line; do
                    # extract pull request number from first position of each line
                    pr_number=$(echo "$line" | awk '{print $1}')
                    
                    # Get checks output from github cli in json format
                    echo "Processing pull request #$pr_number: $pr_title"
                    CHECKS=$(gh pr checks $pr_number --repo $TARGET_REPO --json workflow,state)
                    echo $CHECKS | jq -c '.[]'

                    # output check result to file for debugging
                    echo "pull request #$pr_number results:" >> $CHECKS_RESULT_FILE
                    echo $CHECKS | jq -c '.[]' >> $CHECKS_RESULT_FILE
                    echo "" >> $CHECKS_RESULT_FILE

                    # validate if all checks have a state value of 'success', then declares the pr as 'passed'
                    if echo "$CHECKS" | jq -e 'map(select(.state != "SUCCESS")) | length > 0' > /dev/null; then
                        echo "Not All Checks Passed for pull request #$pr_number"
                    else
                        echo "All checks passed for pull request #$pr_number"
                        echo $line >> $PASSED_PR_FILE
                    fi
                    echo ""
                done < $MATCHED_PR_FILE
            
            - name: merge passed pull requests
              run: |
                # sanity check that file is not empty or missing
                if [ ! -s "$PASSED_PR_FILE" ]; then
                    echo "Input file '$PASSED_PR_FILE' is empty or missing"
                    exit 1
                    fi
                
                # clear out the file content if already exist
                > $MERGED_PR_FILE
                > $UNMERGED_PR_FILE
                
                # merge the pull requests that passed all checks and validate merge success
                while IFS= read -r line; do
                    pr_number=$(echo "$line" | awk '{print $1}')
                
                    echo "Attempting to merge pull request #$pr_number....."
                    gh pr merge $pr_number --repo $TARGET_REPO --merge
                    
                    # checks status to validate that pr is actually merged
                    pr_status=$(gh pr view $pr_number --json state | jq -r '.state')
                
                    if [ $pr_status == "MERGED" ]; then
                        echo "Pull request #$pr_number sucessfully merged. Current State is '$pr_status'"
                        echo "PR #$pr_number" >> $MERGED_PR_FILE
                        gh pr comment $pr_number --body "Schedule merge by $TRIGGER_PHRASE"
                    else
                        echo "Unable to merge #$pr_number. Current State is '$pr_status'"
                        echo "PR #$pr_number" >> $UNMERGED_PR_FILE
                        gh pr comment $pr_number --body "Failed scheduled merge attempt from $TRIGGER_PHRASE"
                    fi
                done < $PASSED_PR_FILE
